management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# excluding individual endpoints provided by the Spring Boot Actuator
# management.endpoints.web.exposure.exclude=health,info

info.app.name=My super cool application
info.app.descriptor=A super crazy application
info.app.version=1.0.0


